---
title: The Coptic Christians of Egypt
author: Andrew Mayo
date: '2017-09-27'
slug: the-coptic-christians-of-egypt
categories:
  - Social Media
tags:
  - Egypt
menu: "main"
thumbnail: "img/coptic.jpg"
---

[The Coptic Christians](http://www.huffingtonpost.com/entry/who-are-egypts-coptic-christians-and-what-do-they-believe_us_58ebc537e4b0c89f912058d5) are the largest Christian community in the Middle East and are made up of approximately nine million Egyptian citizens, or roughly 10% of the population. The Copts can trace their lineage back St. Mark the Apostle and the creation of the Coptic Church sometime in the first century. In 451 AD, the Coptic Church split from the Christian community due to theological differences. Since this split, the Coptic community has been a major target for violence and persecution.

For centuries the Coptic Christians have been oppressed which has led to the destruction of thousands of churches and has forced countless Copts to abandon their faith. Today, Coptic Christians remain to be a major target for terrorist groups, such as ISIS. In the past year, [three bombings](http://www.cnn.com/2017/04/09/middleeast/egypt-coptic-christians/index.html) have been directed at Coptic Churches killing 75 civilians and injuring over 100 more.

The most recent attack occurred in May, where [gunmen assaulted a bus](http://www.bbc.com/news/world-middle-east-40059307) carrying Coptic Christians. 28 people were killed in the gunfire with another 25 wounded, ISIS claimed responsibility for the attack. The bus was traveling from the Minya province to the Monastery of St. Samuel. The attack has led to a three month long state of emergency, however, many Coptic Christians do not believe that the state is doing enough to protect them from terrorist attacks. The Coptic Christians have claimed that the government ordered [state of emergency](https://www.theguardian.com/world/2017/may/28/coptic-christians-accuse-egypt-government) was only done in order to, "calm public opinion" and has done nothing in order to persecute those who have conducted the attacks.